export enum ErrorType {
    RATE_LIMIT = "RATE_LIMIT",
    UNAUTHORIZED = "UNAUTHORIZED",
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    INTERNAL_SERVER = "INTERNAL_SERVER",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
